[project]
name = "kotonoha-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fluxrozin", email = "fluxrozin@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "discord-py>=2.6.4",
    "google-generativeai>=0.8.6",
    "python-dotenv>=1.2.1",
]

[build-system]
requires = ["uv_build>=0.9.24,<0.10.0"]
build-backend = "uv_build"
